// functions/src/integrations/githubPush.ts
import { onCall, HttpsError } from "firebase-functions/v2/https";
import { getFirestore } from "firebase-admin/firestore";
import * as logger from "firebase-functions/logger";
import { GitHubClient, parseGitHubUrl } from "./github/client";

export const pushProjectToGitHub = onCall(async (request) => {
  const uid = request.auth?.uid;
  if (!uid) {
    throw new HttpsError("unauthenticated", "You must be signed in.");
  }

  const projectId = request.data?.projectId as string | undefined;
  const message = (request.data?.message as string | undefined) || "F0: Sync from dashboard";

  if (!projectId) {
    throw new HttpsError("invalid-argument", "projectId is required.");
  }

  const token = process.env.F0_GITHUB_PAT_DEV;
  if (!token) {
    logger.error("F0_GITHUB_PAT_DEV is not set");
    throw new HttpsError("failed-precondition", "GitHub token is not configured on server.");
  }

  const db = getFirestore();
  const projectRef = db.collection("projects").doc(projectId);
  const snap = await projectRef.get();

  if (!snap.exists) {
    throw new HttpsError("not-found", "Project not found.");
  }

  const project = snap.data() as any;

  if (project.ownerUid !== uid) {
    throw new HttpsError("permission-denied", "You do not own this project.");
  }

  const repoUrl: string | undefined = project.integrations?.github?.repoUrl || project.githubRepoUrl;

  if (!repoUrl) {
    throw new HttpsError("failed-precondition", "GitHub repository is not connected.");
  }

  const parsed = parseGitHubUrl(repoUrl);
  if (!parsed) {
    throw new HttpsError("invalid-argument", "Invalid GitHub repo URL.");
  }

  const branch = project.integrations?.github?.branch || "main";

  const client = new GitHubClient({
    owner: parsed.owner,
    repo: parsed.repo,
    token,
  });

  const content = `# F0 Project Sync

Synced from F0 at ${new Date().toISOString()}

Project ID: ${projectId}
Project Name: ${project.name || 'Untitled'}

This file is automatically generated by the F0 platform to track synchronization with GitHub.
`;

  try {
    const result = await client.pushFiles({
      branch,
      message,
      files: [{ path: "F0_SYNC.md", content }],
    });

    await projectRef.update({
      "integrations.github.lastCommit": {
        sha: result.sha,
        message: result.message,
        author: "F0 Agent",
        date: new Date(),
      },
      "integrations.github.lastSync": new Date(),
    });

    return { ok: true, commit: result };
  } catch (err: any) {
    logger.error("pushProjectToGitHub error", err);
    throw new HttpsError("internal", err?.message || "Failed to push to GitHub");
  }
});
