// orchestrator/core/uiBuilder/uiCodegenAgent.ts
// =============================================================================
// Phase 167.2 – UI CodegenAgent
// Generates actual React/TypeScript code from UiGenerationPlan
// =============================================================================

import {
  UiGenerationPlan,
  UiFilePlan,
  UiComponentPlan,
  UiFileChange,
  UiCodegenResult,
  UiStyleHints,
} from './uiGenerationPlanTypes';

// =============================================================================
// Types
// =============================================================================

export interface CodegenOptions {
  useTypeScript?: boolean;
  useTailwind?: boolean;
  useClientDirective?: boolean;
  indentSize?: number;
}

export interface LLMClient {
  complete: (prompt: string) => Promise<string>;
}

// =============================================================================
// ID Generator
// =============================================================================

function generateChangeId(): string {
  return `change_${Date.now()}_${Math.random().toString(36).slice(2, 6)}`;
}

// =============================================================================
// Code Templates
// =============================================================================

const TEMPLATES = {
  pageHeader: (name: string, useClient: boolean) => `${useClient ? "'use client';\n\n" : ''}// =============================================================================
// ${name}
// Generated by F0 UI Builder
// =============================================================================
`,

  imports: (items: string[]) => items.length > 0
    ? items.map(i => i.startsWith("'use client'") ? '' : `import ${i};`).filter(Boolean).join('\n') + '\n\n'
    : '',

  pageFunction: (name: string, content: string) => `export default function ${name}() {
  return (
    <div className="min-h-screen bg-background">
${content}
    </div>
  );
}
`,

  componentFunction: (name: string, content: string, props = '{}') => `export function ${name}(props: ${props}) {
  return (
${content}
  );
}
`,

  cardComponent: (title: string, content: string) => `      <div className="rounded-lg border bg-card p-6 shadow-sm">
        <h3 className="text-lg font-semibold mb-4">${title}</h3>
        <div className="space-y-4">
${content}
        </div>
      </div>`,

  gridContainer: (cols: number, children: string) =>
    `      <div className="grid grid-cols-1 md:grid-cols-${cols} gap-6">
${children}
      </div>`,

  statsCard: (label: string, value: string, icon?: string) =>
    `        <div className="flex items-center justify-between p-4 bg-muted rounded-lg">
          <div>
            <p className="text-sm text-muted-foreground">${label}</p>
            <p className="text-2xl font-bold">${value}</p>
          </div>
          ${icon ? `<div className="text-3xl">${icon}</div>` : ''}
        </div>`,

  dataTable: (headers: string[]) => `      <div className="rounded-lg border">
        <table className="w-full">
          <thead className="bg-muted">
            <tr>
${headers.map(h => `              <th className="px-4 py-3 text-left text-sm font-medium">${h}</th>`).join('\n')}
            </tr>
          </thead>
          <tbody>
            {/* Data rows will be populated here */}
            <tr className="border-t">
${headers.map(() => `              <td className="px-4 py-3 text-sm">-</td>`).join('\n')}
            </tr>
          </tbody>
        </table>
      </div>`,

  filterBar: (filters: string[]) => `      <div className="flex flex-wrap gap-4 p-4 bg-muted rounded-lg mb-6">
${filters.map(f => `        <select className="px-3 py-2 rounded-md border bg-background">
          <option>${f}</option>
        </select>`).join('\n')}
        <button className="px-4 py-2 bg-primary text-primary-foreground rounded-md">
          Apply Filters
        </button>
      </div>`,

  chart: (type: string) => `      <div className="h-64 rounded-lg border p-4">
        <div className="flex items-center justify-center h-full text-muted-foreground">
          {/* ${type} Chart Placeholder */}
          <div className="text-center">
            <div className="text-4xl mb-2">📊</div>
            <p>${type} Chart</p>
          </div>
        </div>
      </div>`,

  form: (fields: { name: string; type: string }[]) => `      <form className="space-y-4 max-w-md">
${fields.map(f => `        <div>
          <label className="block text-sm font-medium mb-1">${f.name}</label>
          <input
            type="${f.type}"
            className="w-full px-3 py-2 rounded-md border bg-background"
            placeholder="Enter ${f.name.toLowerCase()}"
          />
        </div>`).join('\n')}
        <button type="submit" className="w-full px-4 py-2 bg-primary text-primary-foreground rounded-md">
          Submit
        </button>
      </form>`,

  hero: (title: string, subtitle: string) => `      <div className="text-center py-12 px-6">
        <h1 className="text-4xl font-bold mb-4">${title}</h1>
        <p className="text-xl text-muted-foreground mb-8">${subtitle}</p>
        <div className="flex gap-4 justify-center">
          <button className="px-6 py-3 bg-primary text-primary-foreground rounded-md">
            Get Started
          </button>
          <button className="px-6 py-3 border rounded-md">
            Learn More
          </button>
        </div>
      </div>`,

  sidebar: (items: string[]) => `      <aside className="w-64 border-r min-h-screen p-4">
        <nav className="space-y-2">
${items.map(item => `          <a href="#" className="block px-4 py-2 rounded-md hover:bg-muted">
            ${item}
          </a>`).join('\n')}
        </nav>
      </aside>`,

  tabs: (tabNames: string[]) => `      <div>
        <div className="flex border-b mb-4">
${tabNames.map((name, i) => `          <button className="px-4 py-2 ${i === 0 ? 'border-b-2 border-primary' : 'text-muted-foreground'}">
            ${name}
          </button>`).join('\n')}
        </div>
        <div className="p-4">
          {/* Tab content */}
        </div>
      </div>`,
};

// =============================================================================
// Component Generators
// =============================================================================

/**
 * Generate code for a component plan
 */
function generateComponentCode(
  comp: UiComponentPlan,
  styleHints?: UiStyleHints,
  indent = 6,
): string {
  const spaces = ' '.repeat(indent);
  const type = comp.type.toLowerCase();

  // Stats Card Grid
  if (type.includes('statscard') || type.includes('stat')) {
    const stats = (comp.props?.stats as Array<{ label: string; value: string; icon?: string }>) || [
      { label: 'Total Users', value: '1,234' },
      { label: 'Revenue', value: '$12,345' },
      { label: 'Orders', value: '456' },
      { label: 'Growth', value: '+12%' },
    ];
    const cols = Math.min(stats.length, 4);
    const statsContent = stats.map(s => TEMPLATES.statsCard(s.label, s.value, s.icon)).join('\n');
    return TEMPLATES.gridContainer(cols, statsContent);
  }

  // Data Table
  if (type.includes('table') || type.includes('datatable')) {
    const headers = (comp.props?.columns as string[]) || ['Name', 'Status', 'Date', 'Actions'];
    return TEMPLATES.dataTable(headers);
  }

  // Filter Bar
  if (type.includes('filter')) {
    const filters = (comp.props?.filters as string[]) || ['Status', 'Date Range', 'Category'];
    return TEMPLATES.filterBar(filters);
  }

  // Chart
  if (type.includes('chart') || type.includes('graph')) {
    const chartType = (comp.props?.chartType as string) || 'Line';
    return TEMPLATES.chart(chartType);
  }

  // Form
  if (type.includes('form')) {
    const fields = (comp.props?.fields as Array<{ name: string; type: string }>) || [
      { name: 'Name', type: 'text' },
      { name: 'Email', type: 'email' },
      { name: 'Message', type: 'text' },
    ];
    return TEMPLATES.form(fields);
  }

  // Hero Section
  if (type.includes('hero')) {
    const title = (comp.props?.title as string) || 'Welcome';
    const subtitle = (comp.props?.subtitle as string) || 'Get started with our platform';
    return TEMPLATES.hero(title, subtitle);
  }

  // Sidebar
  if (type.includes('sidebar') || type.includes('nav')) {
    const items = (comp.props?.items as string[]) || ['Dashboard', 'Analytics', 'Settings', 'Profile'];
    return TEMPLATES.sidebar(items);
  }

  // Tabs
  if (type.includes('tabs') || type.includes('tabpanel')) {
    const tabs = (comp.props?.tabs as string[]) || ['Overview', 'Details', 'Settings'];
    return TEMPLATES.tabs(tabs);
  }

  // Card
  if (type.includes('card')) {
    const title = (comp.props?.title as string) || comp.name;
    let content = `          <p className="text-muted-foreground">Content for ${title}</p>`;

    if (comp.children && comp.children.length > 0) {
      content = comp.children.map(c => generateComponentCode(c, styleHints, indent + 2)).join('\n');
    }

    return TEMPLATES.cardComponent(title, content);
  }

  // Grid/Container
  if (type.includes('grid') || type.includes('container') || type.includes('layout')) {
    const cols = (comp.props?.columns as number) || 2;
    let children = '';

    if (comp.children && comp.children.length > 0) {
      children = comp.children.map(c => generateComponentCode(c, styleHints, indent + 2)).join('\n');
    } else {
      children = `${spaces}  <div className="p-4 bg-muted rounded">Item 1</div>
${spaces}  <div className="p-4 bg-muted rounded">Item 2</div>`;
    }

    return TEMPLATES.gridContainer(cols, children);
  }

  // Header/Title
  if (type.includes('header') || type.includes('title') || type.includes('heading')) {
    const title = (comp.props?.title as string) || comp.name;
    return `${spaces}<div className="mb-6">
${spaces}  <h1 className="text-2xl font-bold">${title}</h1>
${spaces}  <p className="text-muted-foreground">Manage your ${title.toLowerCase()}</p>
${spaces}</div>`;
  }

  // Button
  if (type.includes('button')) {
    const label = (comp.props?.label as string) || comp.name;
    const variant = (comp.props?.variant as string) || 'primary';
    const variantClass = variant === 'secondary' ? 'bg-secondary text-secondary-foreground' : 'bg-primary text-primary-foreground';
    return `${spaces}<button className="px-4 py-2 ${variantClass} rounded-md">${label}</button>`;
  }

  // Default: Generic div
  let content = `${spaces}  {/* ${comp.type} content */}`;
  if (comp.children && comp.children.length > 0) {
    content = comp.children.map(c => generateComponentCode(c, styleHints, indent + 2)).join('\n');
  }

  return `${spaces}<div className="space-y-4">
${content}
${spaces}</div>`;
}

// =============================================================================
// File Generators
// =============================================================================

/**
 * Generate code for a page file
 */
function generatePageFile(
  filePlan: UiFilePlan,
  plan: UiGenerationPlan,
  options: CodegenOptions = {},
): string {
  const { useClientDirective = true, useTypeScript = true } = options;

  const lines: string[] = [];

  // Header
  lines.push(TEMPLATES.pageHeader(plan.pageName, useClientDirective));

  // Imports
  const imports = filePlan.imports || [];
  if (imports.length > 0) {
    const filteredImports = imports.filter(i => !i.includes("'use client'"));
    if (filteredImports.length > 0) {
      lines.push(filteredImports.map(i => i.startsWith('import') ? i : `import ${i}`).join('\n'));
      lines.push('');
    }
  }

  // Generate component content
  const componentsContent = filePlan.components
    .map(c => generateComponentCode(c, plan.styleHints, 6))
    .join('\n\n');

  // Main page content
  const pageContent = `      {/* Page Header */}
      <header className="border-b">
        <div className="container mx-auto px-6 py-4">
          <h1 className="text-2xl font-bold">${plan.pageName.replace('Page', '')}</h1>
        </div>
      </header>

      {/* Main Content */}
      <main className="container mx-auto px-6 py-8 space-y-8">
${componentsContent}
      </main>`;

  lines.push(TEMPLATES.pageFunction(plan.pageName, pageContent));

  return lines.join('\n');
}

/**
 * Generate code for a component file
 */
function generateComponentFile(
  filePlan: UiFilePlan,
  plan: UiGenerationPlan,
  options: CodegenOptions = {},
): string {
  const lines: string[] = [];

  // Header
  const componentName = filePlan.components[0]?.name || 'Component';
  lines.push(TEMPLATES.pageHeader(componentName, false));

  // Imports
  lines.push("import React from 'react';");
  lines.push('');

  // Props interface
  lines.push(`interface ${componentName}Props {`);
  lines.push('  className?: string;');
  lines.push('}');
  lines.push('');

  // Component content
  const content = filePlan.components
    .map(c => generateComponentCode(c, plan.styleHints, 4))
    .join('\n');

  lines.push(`export function ${componentName}({ className }: ${componentName}Props) {
  return (
    <div className={className}>
${content}
    </div>
  );
}`);

  return lines.join('\n');
}

/**
 * Generate code for a hook file
 */
function generateHookFile(
  filePlan: UiFilePlan,
  plan: UiGenerationPlan,
): string {
  const hookName = filePlan.exports?.[0]?.replace('export ', '') || 'useData';

  return `// =============================================================================
// ${hookName}
// Generated by F0 UI Builder
// =============================================================================

import { useState, useEffect } from 'react';

interface ${hookName.replace('use', '')}State {
  data: any;
  loading: boolean;
  error: string | null;
}

export function ${hookName}() {
  const [state, setState] = useState<${hookName.replace('use', '')}State>({
    data: null,
    loading: true,
    error: null,
  });

  useEffect(() => {
    async function fetchData() {
      try {
        // TODO: Implement data fetching
        setState({ data: null, loading: false, error: null });
      } catch (err) {
        setState({ data: null, loading: false, error: 'Failed to fetch data' });
      }
    }

    fetchData();
  }, []);

  return state;
}
`;
}

// =============================================================================
// Main Codegen Function
// =============================================================================

/**
 * Generate code for all files in a plan
 */
export async function generateUiCode(
  plan: UiGenerationPlan,
  options: CodegenOptions = {},
): Promise<UiCodegenResult> {
  console.log('[167.2][CODEGEN] Generating code for plan:', plan.id);

  const startTime = Date.now();
  const files: UiFileChange[] = [];
  const errors: Array<{ file: string; error: string; recoverable: boolean }> = [];

  for (const filePlan of plan.files) {
    try {
      let content = '';

      switch (filePlan.target.kind) {
        case 'page':
          content = generatePageFile(filePlan, plan, options);
          break;
        case 'component':
          content = generateComponentFile(filePlan, plan, options);
          break;
        case 'hook':
          content = generateHookFile(filePlan, plan);
          break;
        default:
          content = generateComponentFile(filePlan, plan, options);
      }

      const change: UiFileChange = {
        id: generateChangeId(),
        target: filePlan.target,
        action: filePlan.action,
        language: filePlan.target.language || 'tsx',
        newContent: content,
        summary: filePlan.description,
        linesAdded: content.split('\n').length,
        linesRemoved: 0,
        syntaxValid: true, // Assume valid for now
      };

      files.push(change);
    } catch (err) {
      const error = err instanceof Error ? err.message : 'Unknown error';
      console.error('[167.2][CODEGEN] Error generating:', filePlan.target.path, error);
      errors.push({
        file: filePlan.target.path,
        error,
        recoverable: true,
      });
    }
  }

  const result: UiCodegenResult = {
    planId: plan.id,
    projectId: plan.projectId,
    files,
    totalFiles: files.length,
    filesCreated: files.filter(f => f.action === 'create').length,
    filesModified: files.filter(f => f.action === 'modify').length,
    generationTimeMs: Date.now() - startTime,
    errors: errors.length > 0 ? errors : undefined,
  };

  console.log('[167.2][CODEGEN] Generated', files.length, 'files in', result.generationTimeMs, 'ms');

  return result;
}

/**
 * Generate code with LLM assistance for complex components
 */
export async function generateUiCodeWithLLM(
  plan: UiGenerationPlan,
  llmClient: LLMClient,
  options: CodegenOptions = {},
): Promise<UiCodegenResult> {
  console.log('[167.2][CODEGEN] Generating with LLM assistance');

  // First, try template-based generation
  const baseResult = await generateUiCode(plan, options);

  // For complex plans, enhance with LLM
  if (plan.files.length > 3 || plan.files.some(f => f.components.length > 5)) {
    for (const change of baseResult.files) {
      try {
        const enhanced = await enhanceWithLLM(change, plan, llmClient);
        change.newContent = enhanced;
      } catch (err) {
        console.warn('[167.2][CODEGEN] LLM enhancement failed for:', change.target.path);
        // Keep original template-based code
      }
    }
  }

  return baseResult;
}

/**
 * Enhance generated code with LLM
 */
async function enhanceWithLLM(
  change: UiFileChange,
  plan: UiGenerationPlan,
  llmClient: LLMClient,
): Promise<string> {
  const prompt = `You are a React/TypeScript expert. Enhance this generated UI code to be more professional and complete.

<current_code>
${change.newContent}
</current_code>

<style_hints>
${JSON.stringify(plan.styleHints, null, 2)}
</style_hints>

<task>
1. Add proper TypeScript types
2. Add error handling if needed
3. Make the UI more polished
4. Add loading states where appropriate
5. Ensure accessibility (aria labels, etc.)

Return ONLY the enhanced code, no explanations.
</task>`;

  const enhanced = await llmClient.complete(prompt);

  // Extract code from response
  const codeMatch = enhanced.match(/```(?:tsx?|jsx?)?\n([\s\S]*?)```/);
  if (codeMatch) {
    return codeMatch[1];
  }

  // If no code block, check if it looks like valid code
  if (enhanced.includes('export') && enhanced.includes('function')) {
    return enhanced;
  }

  // Fall back to original
  return change.newContent || '';
}

// =============================================================================
// Utility Exports
// =============================================================================

export {
  generateComponentCode,
  generatePageFile,
  generateComponentFile,
  generateHookFile,
  TEMPLATES,
};

console.log('[167.2][UI_BUILDER] CodegenAgent loaded');
