// src/app/api/agents/run-plan/route.ts
// =============================================================================
// Phase 155.7 – Run Plan API Route
// Receives goal from UI, publishes TASK_PROPOSAL to agent bus
// =============================================================================

import { NextRequest, NextResponse } from 'next/server';

// Import orchestrator singleton (will be created next)
import { getOrchestratorBus } from '@/lib/agents/orchestratorBus';

interface RunPlanRequest {
  projectId: string;
  goal: string;
  userId?: string;
  conversationId?: string;
  constraints?: {
    maxSteps?: number;
    preferSafeMode?: boolean;
    allowShell?: boolean;
    allowBrowser?: boolean;
  };
}

function generateId(prefix = 'msg'): string {
  return `${prefix}_${Math.random().toString(36).slice(2, 10)}`;
}

export async function POST(request: NextRequest) {
  console.log('[155.7][API] POST /api/agents/run-plan');

  try {
    const body: RunPlanRequest = await request.json();
    const { projectId, goal, userId, conversationId, constraints } = body;

    // Validate required fields
    if (!projectId) {
      return NextResponse.json(
        { success: false, error: 'projectId is required' },
        { status: 400 }
      );
    }

    if (!goal || typeof goal !== 'string' || goal.trim().length === 0) {
      return NextResponse.json(
        { success: false, error: 'goal is required and must be a non-empty string' },
        { status: 400 }
      );
    }

    // Get orchestrator bus singleton
    const bus = getOrchestratorBus();

    // Generate message ID for tracking
    const messageId = generateId('task_proposal');
    const timestamp = new Date().toISOString();

    // Publish TASK_PROPOSAL to planner
    await bus.publish({
      id: messageId,
      timestamp,
      from: 'conversation',
      to: 'planner',
      kind: 'TASK_PROPOSAL',
      context: {
        projectId,
        workspaceId: 'web',
        userId: userId || 'anonymous',
        conversationId: conversationId || generateId('conv'),
      },
      safety: { level: 'medium' },
      payload: {
        goal: goal.trim(),
        projectId,
        constraints: constraints || {},
      },
    });

    console.log('[155.7][API] TASK_PROPOSAL published:', messageId);

    // Return success with message ID
    // The plan ID will be generated by PlannerAgent and stored in Firestore
    // Client can listen to Firestore for real-time updates
    return NextResponse.json({
      success: true,
      messageId,
      message: 'Task proposal submitted to agent planner',
    });
  } catch (error) {
    console.error('[155.7][API] Error:', error);

    const message = error instanceof Error ? error.message : 'Unknown error';
    return NextResponse.json(
      { success: false, error: message },
      { status: 500 }
    );
  }
}

// GET endpoint to check orchestrator status
export async function GET() {
  try {
    const bus = getOrchestratorBus();

    return NextResponse.json({
      success: true,
      status: 'ready',
      message: 'Orchestrator bus is running',
    });
  } catch (error) {
    const message = error instanceof Error ? error.message : 'Unknown error';
    return NextResponse.json(
      { success: false, status: 'error', error: message },
      { status: 500 }
    );
  }
}

console.log('[155.7][API] run-plan route loaded');
